sudo: required
language: generic
services:
  - docker
before_install:
  - docker build -t nikitaproks/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true nikitaproks/react-test npm test

after_success:
  - docker build -t nikitaproks/multi-client ./client
  - docker build -t nikitaproks/multi-nginx ./nginx
  - docker build -t nikitaproks/multi-server ./server
  - docker build -t nikitaproks/multi-worker ./worker
  # Log into the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push to docker hub
  - docker push nikitaproks/multi-client
  - docker push nikitaproks/multi-nginx
  - docker push nikitaproks/multi-server
  - docker push nikitaproks/multi-worker
